### ISSUE TITLE
Add TimeZone example in doc

### ISSUE THREAD

**Issue by marcflausino** [ansible/community-docs#30]
Hello, 

I lost a few hours trying to understand why i got an error like '**No such parameter**' while setting '**timezone**' with **postgresql_set**.

Finally i ended up on this post : [https://github.com/ansible-collections/community.postgresql/issues/41](https://github.com/ansible-collections/community.postgresql/issues/41)

I'm sure, many will have the same troubleshoot with that parameter so i guess it would be nice to add an example on the documentation with that TimeZone name, and maybe add an explanation or a warning somehow.

What do you think ?

**Comment by Andersson007** [comment]
@marcflausino hello, thanks for reporting the issue!
Could you please copy it into https://github.com/ansible-collections/community.postgresql/issues/ and close this one?
This repo is for general contributor documentation, e.g. tutorials, guidelines, etc.

**Comment by marcflausino** [comment]
moved to : https://github.com/ansible-collections/community.postgresql/issues/139

**Comment by Andersson007** [comment]
Thanks!
