### ISSUE TITLE
searching the docs on a specific ansible version always returns links to latest

### ISSUE THREAD

**Issue by SvenMW** [ansible/community-docs#43]
how to reproduce:

visit https://docs.ansible.com/ansible/2.9/

search via the box in the left top corner, any topic will suffice, e.g." inventory"

click on the first link, you get to:

https://docs.ansible.com/ansible/latest/plugins/inventory.html

but I specifically went to the 2.9 version docs, so I want to search the 2.9 docs and don't want results from another version.

Thanks

**Comment by Andersson007** [comment]
@SvenMW thanks for reporting this?
@samccann @ariordan-redhat where is the right place for the issue?

**Comment by samccann** [comment]
This already exists as an issue in the ansible/ansible repo. I'll dig up the link and add it here.

It's not a 'simple/quick' thing to solve, but it's I problem I've hit myself for sure and it's more than annoying :-(

**Comment by samccann** [comment]
Here it is - https://github.com/ansible/ansible/issues/72106

That issue links to a couple of others related to search so I'll close this one in favor of those. Thanks @SvenMW for reporting this! Even thought it's been reported, it helps us prioritize this as something we really need to improve on...

**Comment by Andersson007** [comment]
@SvenMW @samccann thank you!

**Comment by SvenMW** [comment]
it's greatly appreciated @samccann you're working on this, this would save me and others a lot of time, checking links and if content changed between versions :+1:
