### ISSUE TITLE
Embed the existing documents into docs.ansible.com/ansible/devel/community/ or leave them here.

### ISSUE THREAD

**Issue by Andersson007** [ansible/community-docs#7]
We now have 1) contributing guidelines, 2) review checklist, 3) quick start dev guide living here.

The idea of the documents, besides just being in the doc for information, is to refer to them from the collections' CONTRIBUTING.mds. I'm going to do it as soon as possible.

As development of a new site is a long-term process, to make the above possible, there can be 2 ways:
1) leave the documents here (in the root) and add refs to CONTRIBUTING.mds across the collections. Later the dir structure will be reorganized and we'll have to fix the refs in the collections (it's not a problem).
2) move them to `docs.ansible.com/ansible/devel/community/` and add refs to CONTRIBUTING.mds across the collections. Then, when the new community site has been created, we could move them to new permanent place and fix refs in the collections. In this scenario, people can find the documents on our current website.

What do you think?

**Comment by Andersson007** [comment]
CC @gundalow @acozine @samccann @felixfontein

**Comment by samccann** [comment]
We were planning on incorporating them into docs.ansible.com (aka #2 above). We were waiting for them to 'settle' a bit since it was changing rapidly for a time and easier for folks to change where they are now vs in ansible/ansible and waiting on us to review/merge and republish etc. We're also crunched for time, so even though they've settled, we haven't moved them yet.

**Comment by samccann** [comment]
fwiw I'm in the process of moving these files over. 

- [ ] maintaining - moved over via https://github.com/ansible/ansible/pull/76976
- [ ] create_pr_quick_start_guide.rst - will move this one next.

**Comment by Andersson007** [comment]
@samccann i marked the second checkbox in your comment above as complete, thanks!

Looks like except https://github.com/ansible/community-docs/blob/main/review_checklist.rst everything has been moved

**Comment by Andersson007** [comment]
@samccann great @samccann thank you much!
